# backend/app/reports/action_packet.py
import hashlib
from datetime import datetime
from ..schemas.snapshot import LawfulActionPacket
from ..schemas.attribution import VASPAttributionCandidate

class ActionPacketGenerator:
    """
    Drafts review-ready Lawful Action Packets (Section 91 CrPC / MLAT / FIU requests)
    for authorized law enforcement officers.
    NEVER automatically executes or sends requests.
    """

    @classmethod
    def generate_packet(
        cls,
        case_id: str,
        investigator: str,
        suspect_wallet: str,
        chain: str,
        candidate: VASPAttributionCandidate
    ) -> LawfulActionPacket:
        now_str = datetime.utcnow().strftime("%Y-%m-%d %H:%M:%S UTC")
        
        preservation_draft = f"""
OFFICIAL PRESERVATION NOTICE UNDER SECTION 91 CrPC / IT ACT (DRAFT FOR OFFICER REVIEW)
---------------------------------------------------------------------------------------
To: Legal Compliance Department, {candidate.entity_name}
From: Cyber Crime Police Station / Financial Investigation Unit
Date of Notice: {now_str}
Case Reference: {case_id}
Investigating Officer: {investigator}

SUBJECT: URGENT PRESERVATION OF TRANSACTION LOGS & KYC RECORDS

1. This agency is investigating financial fraud involving illicit cryptocurrency flows.
2. Blockchain intelligence indicates that funds originating from Suspect Wallet:
   {suspect_wallet} ({chain})
   were transferred to custodial deposit infrastructure associated with {candidate.entity_name}:
   Deposit Wallet: {candidate.terminal_deposit_address or "N/A"}
   Shortest Topological Path: {candidate.shortest_path_hops} hops
   Attribution Confidence: {candidate.confidence_score}% ({candidate.confidence_band})

3. YOU ARE HEREBY REQUESTED TO IMMEDIATELY PRESERVE:
   a. All account registration details, KYC documents, phone numbers, and IP connection logs.
   b. All deposit, withdrawal, and internal ledger logs linked to the above deposit infrastructure.
   c. Fiat bank accounts associated with liquidation withdrawals.

NOTICE: This document is an investigator draft generated by the Crypto Investigation Copilot.
Official issuance requires authorization and physical/digital signature by the Investigating Officer.
"""

        disclosure_draft = f"""
FORMAL DISCLOSURE REQUISITION (SECTION 91 CrPC / STATUTORY NOTICE DRAFT)
------------------------------------------------------------------------
To: Designated Grievance / Nodal Officer, {candidate.entity_name}
Case File: {case_id}

Requisition for production of documents and evidentiary records concerning transactions:
{', '.join(candidate.supporting_tx_ids[:5])}

Please supply certified copies of the identity records and banking rails for the account
holding custody of deposit address: {candidate.terminal_deposit_address or "Identified Infrastructure"}
within 72 hours of official receipt.
"""

        disclaimer = (
            "STATUTORY LEGAL NOTICE & DISCLAIMER:\n"
            "This Lawful Action Packet is an automated intelligence draft prepared solely to assist "
            "authorized investigating officers. It does NOT constitute an automated legal order. "
            "Beneficiary identity is NOT established from on-chain clustering alone. "
            "Any submission to exchanges must be formally reviewed and signed by an authorized officer."
        )

        packet_body = preservation_draft + disclosure_draft + disclaimer
        integrity_hash = hashlib.sha256(packet_body.encode("utf-8")).hexdigest()

        return LawfulActionPacket(
            packet_id=f"act_{case_id}_{int(datetime.utcnow().timestamp())}",
            case_id=case_id,
            suspect_wallet=suspect_wallet,
            chain=chain,
            attributed_vasp=candidate.entity_name,
            attribution_confidence=f"{candidate.confidence_score}% ({candidate.confidence_band})",
            operator_role="VASP-Controlled Deposit Infrastructure",
            beneficiary_identity="NOT ESTABLISHED (Awaiting Off-Chain KYC)",
            integrity_hash_sha256=integrity_hash,
            preservation_notice_draft=preservation_draft.strip(),
            disclosure_request_draft=disclosure_draft.strip(),
            statutory_disclaimer=disclaimer
        )
