# backend/app/blockchain/providers/bitquery/__init__.py
from .client import BitqueryClient
from .provider import BitqueryProvider
from .mapper import BitqueryEVMMapper
from .pagination import encode_cursor, decode_cursor
from .queries import (
    ETHEREUM_TRANSACTIONS_OUTGOING_QUERY,
    ETHEREUM_TRANSACTIONS_INCOMING_QUERY,
    ETHEREUM_TRANSACTIONS_ANY_QUERY,
    ETHEREUM_TRANSACTION_BY_HASH_QUERY,
    ETHEREUM_TRANSFERS_OUTGOING_QUERY,
    ETHEREUM_TRANSFERS_INCOMING_QUERY,
    ETHEREUM_TRANSFERS_ANY_QUERY,
    ETHEREUM_TRANSFERS_BY_TX_HASHES_QUERY,
    ETHEREUM_BLOCK_BY_NUMBER_QUERY,
    ETHEREUM_BLOCK_BY_HASH_QUERY,
    ETHEREUM_ASSET_METADATA_QUERY,
)

__all__ = [
    "BitqueryClient",
    "BitqueryProvider",
    "BitqueryEVMMapper",
    "encode_cursor",
    "decode_cursor",
    "ETHEREUM_TRANSACTIONS_OUTGOING_QUERY",
    "ETHEREUM_TRANSACTIONS_INCOMING_QUERY",
    "ETHEREUM_TRANSACTIONS_ANY_QUERY",
    "ETHEREUM_TRANSACTION_BY_HASH_QUERY",
    "ETHEREUM_TRANSFERS_OUTGOING_QUERY",
    "ETHEREUM_TRANSFERS_INCOMING_QUERY",
    "ETHEREUM_TRANSFERS_ANY_QUERY",
    "ETHEREUM_TRANSFERS_BY_TX_HASHES_QUERY",
    "ETHEREUM_BLOCK_BY_NUMBER_QUERY",
    "ETHEREUM_BLOCK_BY_HASH_QUERY",
    "ETHEREUM_ASSET_METADATA_QUERY",
]
